services:
  hnrobert-homepage:
    container_name: hnrobert-homepage
    image: ghcr.io/hnrobert/hnrobert-homepage:latest
    ports:
      - 9970:9970 # HTTP port
      - 9977:9977 # HTTPS port
    restart: always
    volumes:
      - /volume2/docker/hnrobert-homepage/ssl:/root/.config/ssl
      - /volume2/docker/hnrobert-homepage/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: >
      sh -c "
        # Create empty SSL certificates if they don't exist
        if [ ! -f /root/.config/ssl/cert.crt ]; then
          echo 'Creating empty SSL certificate file'
          touch /root/.config/ssl/cert.crt
        fi
        
        if [ ! -f /root/.config/ssl/cert.key ]; then
          echo 'Creating empty SSL key file'
          touch /root/.config/ssl/cert.key
        fi
        
        # Start nginx
        echo 'Starting Nginx...'
        nginx -g 'daemon off;'
      "
    network_mode: host
