services:
  hnrobert-homepage:
    container_name: hnrobert-homepage
    image: ghcr.io/hnrobert/hnrobert-homepage:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - '9970:3000'
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
  
  hnrobert-homepage-nginx:
    container_name: hnrobert-homepage-nginx
    image: nginx:alpine
    volumes:
      - /volume2/docker/hnrobert-homepage/ssl:/root/.config/ssl
      - /volume2/docker/hnrobert-homepage/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hnrobert-homepage
    restart: always
    network_mode: host
